version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sklep-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sklep_db
      MYSQL_USER: sklep_user
      MYSQL_PASSWORD: sklep_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sklep-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: sklep_user
      PMA_PASSWORD: sklep_pass
    ports:
      - "8080:80"
    depends_on:
      - db

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: sklep-backend
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=mysql+pymysql://sklep_user:sklep_pass@db:3306/sklep_db

volumes:
  db_data:
