services:
  db:
    image: mysql:8.0
    container_name: sklep-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sklep_db
      MYSQL_USER: sklep_user
      MYSQL_PASSWORD: sklep_pass
    ports:
      - "3306:3306"

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://sklep_user:sklep_pass@sklep-db:3306/sklep_db
